class Solution {
    public int numberOfSpecialChars(String word) {
        int count=0;
        HashSet<Character>set=new HashSet<>();
        for(char c:word.toCharArray()){
            set.add(c);
        }
        for(char c:word.toCharArray()){
            if(c=='a'){
            if(set.contains('A')){
                count++;
                set.remove('A');
            }
            }
            if(c=='b'){
            if(set.contains('B')){
                count++;
                set.remove('B');
            }
            }if(c=='c'){
            if(set.contains('C')){
                count++;
                set.remove('C');
            }
            }if(c=='d'){
            if(set.contains('D')){
                count++;
                set.remove('D');
            }
            }if(c=='e'){
            if(set.contains('E')){
                count++;
                set.remove('E');
            }
            }if(c=='f'){
            if(set.contains('F')){
                count++;
                set.remove('F');
            }
            }if(c=='g'){
            if(set.contains('G')){
                count++;
                set.remove('G');
            }
            }if(c=='h'){
            if(set.contains('H')){
                count++;
                set.remove('H');
            }
            }if(c=='i'){
            if(set.contains('I')){
                count++;
                set.remove('I');
            }
            }if(c=='j'){
            if(set.contains('J')){
                count++;
                set.remove('J');
            }
            }if(c=='k'){
            if(set.contains('K')){
                count++;
                set.remove('K');
            }
            }if(c=='l'){
            if(set.contains('L')){
                count++;
                set.remove('L');
            }
            }if(c=='m'){
            if(set.contains('M')){
                count++;
                set.remove('M');
            }
            }if(c=='n'){
            if(set.contains('N')){
                count++;
                set.remove('N');
            }
            }if(c=='o'){
            if(set.contains('O')){
                count++;
                set.remove('O');
            }
            }if(c=='p'){
            if(set.contains('P')){
                count++;
                set.remove('P');
            }
            }if(c=='q'){
            if(set.contains('Q')){
                count++;
                set.remove('Q');
            }
            }if(c=='r'){
            if(set.contains('R')){
                count++;
                set.remove('R');
            }
            }if(c=='s'){
            if(set.contains('S')){
                count++;
                set.remove('S');
            }
            }if(c=='t'){
            if(set.contains('T')){
                count++;
                set.remove('T');
            }
            }if(c=='u'){
            if(set.contains('U')){
                count++;
                set.remove('U');
            }
            }if(c=='v'){
            if(set.contains('V')){
                count++;
                set.remove('V');
            }
            }if(c=='w'){
            if(set.contains('W')){
                count++;
                set.remove('W');
            }
            }if(c=='x'){
            if(set.contains('X')){
                count++;
                set.remove('X');
            }
            }if(c=='y'){
            if(set.contains('Y')){
                count++;
                set.remove('Y');
            }
            }if(c=='z'){
            if(set.contains('Z')){
                count++;
                set.remove('Z');
            }
            }

        }
        return count;
    }
}